#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    from trr_backend.db import pg
    from trr_backend.utils.env import load_env
except ModuleNotFoundError:  # pragma: no cover - script execution convenience
    repo_root = Path(__file__).resolve().parents[2]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))
    from trr_backend.db import pg
    from trr_backend.utils.env import load_env


BACKEND_ROOT = Path(__file__).resolve().parents[2]
WORKSPACE_ROOT = BACKEND_ROOT.parent
DEFAULT_OUTPUT = WORKSPACE_ROOT / "docs/workspace/supabase-rls-grants-review.md"

RLS_SQL = """
SELECT
  n.nspname AS schema_name,
  c.relname AS table_name,
  c.relrowsecurity AS rls_enabled,
  c.relforcerowsecurity AS rls_forced
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r', 'p')
  AND n.nspname IN ('public', 'core', 'admin', 'firebase_surveys', 'social')
ORDER BY n.nspname, c.relname
"""

GRANTS_SQL = """
SELECT
  table_schema,
  table_name,
  grantee,
  privilege_type
FROM information_schema.role_table_grants
WHERE table_schema IN ('public', 'core', 'admin', 'firebase_surveys', 'social')
  AND grantee IN ('anon', 'authenticated', 'service_role')
ORDER BY table_schema, table_name, grantee, privilege_type
"""


def _bool_text(value: Any) -> str:
    return "yes" if bool(value) else "no"


def _table(rows: list[dict[str, Any]], columns: list[str]) -> list[str]:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join("---" for _ in columns) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(row.get(column, "")) for column in columns) + " |")
    return lines


def render_snapshot() -> str:
    rls_rows = pg.fetch_all(RLS_SQL, [])
    grant_rows = pg.fetch_all(GRANTS_SQL, [])
    normalized_rls = [
        {
            "schema": row.get("schema_name"),
            "table": row.get("table_name"),
            "rls_enabled": _bool_text(row.get("rls_enabled")),
            "rls_forced": _bool_text(row.get("rls_forced")),
        }
        for row in rls_rows
    ]
    normalized_grants = [
        {
            "schema": row.get("table_schema"),
            "table": row.get("table_name"),
            "grantee": row.get("grantee"),
            "privilege": row.get("privilege_type"),
        }
        for row in grant_rows
    ]
    lines = [
        "# Supabase RLS And Grants Review",
        "",
        "Generated by `TRR-Backend/scripts/db/rls_grants_snapshot.py`. This file contains no secret values.",
        "",
        "## RLS Inventory",
        "",
        *_table(normalized_rls, ["schema", "table", "rls_enabled", "rls_forced"]),
        "",
        "## Role Grants",
        "",
        *_table(normalized_grants, ["schema", "table", "grantee", "privilege"]),
        "",
        "## Review Notes",
        "",
        "- Mark every intentional public read here.",
        "- Link corrective migrations from the affected row.",
        "- Re-run this snapshot after grant or policy changes.",
    ]
    return "\n".join(lines) + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write a markdown RLS/grants snapshot.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def resolve_output_path(path: Path) -> Path:
    if path.is_absolute():
        return path
    return (Path.cwd() / path).resolve()


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    load_env()
    rendered = render_snapshot()
    output = resolve_output_path(args.output)
    if args.check:
        existing = output.read_text(encoding="utf-8") if output.is_file() else ""
        if existing != rendered:
            print(f"[rls-grants-snapshot] ERROR: {output} is stale.", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
