begin;

create schema if not exists admin;

create table if not exists admin.network_streaming_overrides (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('network', 'streaming')),
  entity_key text not null,
  display_name_override text,
  wikidata_id_override text,
  wikipedia_url_override text,
  logo_source_urls_override jsonb not null default '[]'::jsonb,
  source_priority_override text[] not null default array[]::text[],
  aliases_override text[] not null default array[]::text[],
  notes text,
  is_active boolean not null default true,
  updated_by text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (entity_type, entity_key)
);

create index if not exists network_streaming_overrides_type_active_idx
  on admin.network_streaming_overrides (entity_type, is_active, entity_key);

create table if not exists admin.network_streaming_completion (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('network', 'streaming')),
  entity_key text not null,
  entity_id text,
  display_name text not null,
  available_show_count int not null default 0,
  added_show_count int not null default 0,
  wikidata_id text,
  wikipedia_url text,
  hosted_logo_url text,
  hosted_logo_black_url text,
  hosted_logo_white_url text,
  base_logo_format text not null default 'unknown'
    check (base_logo_format in ('png', 'svg', 'unknown')),
  resolution_status text not null default 'manual_required'
    check (resolution_status in ('resolved', 'manual_required', 'failed')),
  resolution_reason text,
  source_priority text[] not null default array[]::text[],
  last_run_id text,
  last_attempt_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (entity_type, entity_key)
);

create index if not exists network_streaming_completion_status_idx
  on admin.network_streaming_completion (resolution_status, entity_type, entity_key);

create table if not exists admin.network_streaming_completion_attempts (
  id bigint generated by default as identity primary key,
  completion_id uuid not null references admin.network_streaming_completion (id) on delete cascade,
  run_id text not null,
  entity_type text not null check (entity_type in ('network', 'streaming')),
  entity_key text not null,
  source text not null check (source in ('override', 'tmdb', 'wikimedia', 'official', 'catalog', 'variant')),
  attempt_url text,
  outcome text not null check (outcome in ('success', 'failed', 'skipped')),
  failure_reason text,
  duration_ms int,
  details jsonb not null default '{}'::jsonb,
  attempted_at timestamptz not null default now()
);

create index if not exists network_streaming_completion_attempts_completion_idx
  on admin.network_streaming_completion_attempts (completion_id, attempted_at desc);

create index if not exists network_streaming_completion_attempts_run_idx
  on admin.network_streaming_completion_attempts (run_id, attempted_at desc);

grant usage on schema admin to service_role;
grant all privileges on table admin.network_streaming_overrides to service_role;
grant all privileges on table admin.network_streaming_completion to service_role;
grant all privileges on table admin.network_streaming_completion_attempts to service_role;
grant usage, select on all sequences in schema admin to service_role;

commit;
